// Exporter — Phase 4
// Assembles the final portable markdown context snapshot

export function exportToMarkdown(compressed, platform) {
  const { verbatim, summaries } = compressed
  const now = new Date().toISOString().split('T')[0]

  // Categorize verbatim turns
  const code = verbatim.filter(t => t.type === 'code')
  const decisions = verbatim.filter(t => t.type === 'decision')
  const requirements = verbatim.filter(t => t.type === 'requirement')
  const errors = verbatim.filter(t => t.type === 'error')

  const lines = []

  // Header
  lines.push(`# Context Snapshot`)
  lines.push(``)
  lines.push(`- **Date:** ${now}`)
  lines.push(`- **Source Platform:** ${platform || 'unknown'}`)
  lines.push(`- **Generated by:** Context Migration Tool (CMT)`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // Instructions for receiving model
  lines.push(`## Instructions for Receiving Model`)
  lines.push(``)
  lines.push(`This file is a compressed snapshot of a previous conversation. `)
  lines.push(`Read all sections below to understand the full context before responding. `)
  lines.push(`Continue from the "Current State & Next Steps" section.`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // Project goal — derived from requirements
  if (requirements.length > 0) {
    lines.push(`## Project Goal & Requirements`)
    lines.push(``)
    requirements.forEach(t => {
      lines.push(t.content)
      lines.push(``)
    })
    lines.push(`---`)
    lines.push(``)
  }

  // Key decisions
  if (decisions.length > 0) {
    lines.push(`## Key Decisions Made`)
    lines.push(``)
    decisions.forEach(t => {
      lines.push(`- ${t.content.split('\n')[0]}`)
    })
    lines.push(``)
    lines.push(`---`)
    lines.push(``)
  }

  // Conversation summary
  if (summaries.length > 0) {
    lines.push(`## Conversation Summary`)
    lines.push(``)
    summaries.forEach(s => {
      lines.push(s.content)
      lines.push(``)
    })
    lines.push(`---`)
    lines.push(``)
  }

  // Critical artifacts — code blocks
  if (code.length > 0) {
    lines.push(`## Critical Artifacts`)
    lines.push(``)
    code.forEach((t, i) => {
      lines.push(`### Artifact ${i + 1}`)
      lines.push(``)
      // If content already has code fences, preserve as-is
      if (t.content.includes('```')) {
        lines.push(t.content)
      } else {
        lines.push('```')
        lines.push(t.content)
        lines.push('```')
      }
      lines.push(``)
    })
    lines.push(`---`)
    lines.push(``)
  }

  // Errors and debug output
  if (errors.length > 0) {
    lines.push(`## Errors & Debug Context`)
    lines.push(``)
    errors.forEach(t => {
      lines.push('```')
      lines.push(t.content)
      lines.push('```')
      lines.push(``)
    })
    lines.push(`---`)
    lines.push(``)
  }

  // Current state — last few verbatim turns as current state indicator
  const lastTurns = verbatim.slice(-3)
  if (lastTurns.length > 0) {
    lines.push(`## Current State & Next Steps`)
    lines.push(``)
    lines.push(`The conversation ended at this point. Continue from here:`)
    lines.push(``)
    lastTurns.forEach(t => {
      lines.push(`**${t.role === 'user' ? 'User' : 'Assistant'}:** ${t.content.split('\n')[0]}`)
      lines.push(``)
    })
  }

  return lines.join('\n')
}
